# Generated by Django 5.2.4 on 2025-08-04 07:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astha_therapy_center_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Therapist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Full name (e.g., Dr. Emily Johnson)', max_length=100)),
                ('title', models.CharField(help_text='Professional title (e.g., Senior Physiotherapist)', max_length=100)),
                ('experience_years', models.PositiveIntegerField(help_text='Years of experience')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('bio_short', models.TextField(help_text='Short bio for cards and lists', max_length=500)),
                ('bio_full', models.TextField(help_text='Full biography for detail page')),
                ('personal_info', models.TextField(blank=True, help_text='Personal information section', null=True)),
                ('awards_info', models.TextField(blank=True, help_text='Awards and honors information', null=True)),
                ('profile_image', models.ImageField(help_text='Main profile photo', upload_to='therapist_images/')),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('skill_patient_diagnosis', models.PositiveIntegerField(default=0, help_text='Patient diagnosis skill percentage (0-100)')),
                ('skill_treatment_planning', models.PositiveIntegerField(default=0, help_text='Treatment planning skill percentage (0-100)')),
                ('skill_manual_therapy', models.PositiveIntegerField(default=0, help_text='Manual therapy techniques skill percentage (0-100)')),
                ('skill_exercise_prescription', models.PositiveIntegerField(default=0, help_text='Exercise prescription skill percentage (0-100)')),
                ('skill_electrotherapy', models.PositiveIntegerField(default=0, help_text='Electrotherapy skill percentage (0-100)')),
                ('skill_interpersonal', models.PositiveIntegerField(default=0, help_text='Interpersonal skills percentage (0-100)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this therapist profile should be displayed')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order for displaying therapists (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Therapist',
                'verbose_name_plural': 'Therapists',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
