# Generated by Django 5.2.4 on 2025-08-04 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astha_therapy_center_web', '0002_therapist'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly name', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of the category')),
                ('is_active', models.BooleanField(default=True, help_text='Show this category on the website')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly name', unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of the tag')),
                ('is_active', models.BooleanField(default=True, help_text='Show this tag on the website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog Tag',
                'verbose_name_plural': 'Blog Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Post title', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly title', max_length=200, unique=True)),
                ('excerpt', models.TextField(blank=True, help_text='Brief summary for blog listing', max_length=500)),
                ('content', models.TextField(help_text='Main content with rich formatting support')),
                ('content_html', models.TextField(blank=True, help_text='HTML version of content (auto-generated)')),
                ('featured_image', models.ImageField(blank=True, help_text='Featured image for the post', null=True, upload_to='blog_images/')),
                ('meta_title', models.CharField(blank=True, help_text='SEO title (if different from post title)', max_length=200)),
                ('meta_description', models.TextField(blank=True, help_text='SEO description', max_length=300)),
                ('meta_keywords', models.CharField(blank=True, help_text='SEO keywords', max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, help_text='Publication date and time', null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show this post as featured')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('allow_comments', models.BooleanField(default=True, help_text='Allow comments on this post')),
                ('allow_sharing', models.BooleanField(default=True, help_text='Allow social media sharing')),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Number of times this post has been viewed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='astha_therapy_center_web.blogcategory')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='astha_therapy_center_web.blogtag')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
